### ISSUE TITLE
USER STORY: Publish a pole on the Top page to collect users feedback

### ISSUE THREAD

**Issue by AtsukoCoffey** [AtsukoCoffey/love-running#1]
In order to **increase levels of user interaction** as a **Site Owner**, I can **implement a pole in Top-page and add votes and keep record of all previous polls including voting details**.

## Acceptance Criteria:
* Acceptance Criteria 1: The pole is placed article section in Top-page 
* Acceptance Criteria 2: The pole is used radio button
* Acceptance Criteria 3: The pole will remember the user's cookie to prevent to vote again
* Acceptance Criteria 4: The pole will make the css result data
* a. The poll should disappear at 11:59 PM on the target date
* b. The real estate of the "Poll" should be reserved on the home page. a message that says "Stay tuned, a new poll is coming soon"
* c. The administrator expiry date should be at least 3 days after the current date.

## Tasks
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker 
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create JavaScript function to validate the expiry date is at least after 3 days. 
- [ ]  Create a job to check expired Polls everyday at 11:59PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
