### ISSUE TITLE
USER STORY: Add comment on the poll

### ISSUE THREAD

**Issue by AtsukoCoffey** [AtsukoCoffey/love-running#3]
In order to **provide additional thoughts beyond the response options** as a **user**, I can **add a comment before I submit my poll response**

## Acceptance Criteria:

* Acceptance Criteria 1: Use text box for the comment area and it's optional
* Acceptance Criteria 2: This displays on the confirmation page before submit
* Acceptance Criteria 3: This item is added to the data that is downloadable for the site owner

## Tasks
- [ ] Add text box area
- [ ] Display on the confirmation page
- [ ] Modify the the code to produce the data
- [ ] Test the function
