### ISSUE TITLE
USER STORY: Add expiry date on the poll

### ISSUE THREAD

**Issue by AtsukoCoffey** [AtsukoCoffey/love-running#4]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll**

#5 Link to the closed PBI

## Acceptance Criteria:

* Acceptance Criteria 1: Use calendar display
* Acceptance Criteria 2: Evaluate the date is at least 3 days after the input day
* Acceptance Criteria 3: 

## Tasks
- [ ] Implement the date with calendar display
- [ ] Code for the evaluate the date is 3 days after the input day
- [ ] Test the function
